In [2]:
import numpy as np
import cv2

In [10]:
img = cv2.imread('./3_cars.jpg') # bgr

In [8]:
cv2.imshow('original_image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img.shape

(795, 1200, 3)

In [11]:
b,g,r = cv2.split(img)

In [12]:
print(b)

[[43 33 36 ... 19 27 39]
 [28 12 11 ...  2  7 20]
 [28 15 16 ...  3 12 25]
 ...
 [60 49 48 ... 27 33 43]
 [58 48 47 ... 27 33 43]
 [75 64 63 ... 44 50 60]]


In [14]:
b.shape,g.shape,r.shape

((795, 1200), (795, 1200), (795, 1200))

In [16]:
cv2.imshow('blue image',b)
cv2.imshow('green_image',g)
cv2.imshow('red_image',r)
cv2.imshow('original',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Convert Color

In [6]:
img1 = cv2.imread('./beach.jpg')  # bgr

In [7]:
cv2.imshow('orginal-bgr',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 1. BGR to gray
gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

# 2. BGR to RGB 


# 3. BGR to HSV


# 4. BGR to LAB

